#!/usr/bin/env python3
"""Index the intrinsic pixel size of every live image into _data/imagemeta.yml.

The figure include uses this to:
  - emit width/height attributes, so nothing shifts while loading
  - cap the displayed width at half the intrinsic width, which keeps every image
    at 2x on a retina screen and makes upscaling structurally impossible

Run after adding images:  python3 tools/index-images.py
"""

import os
import sys

try:
    from PIL import Image
except ImportError:
    print("index-images: Pillow not installed; skipping", file=sys.stderr)
    sys.exit(0)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MEDIA = os.path.join(ROOT, "assets", "media")
OUT = os.path.join(ROOT, "_data", "imagemeta.yml")
EXTS = (".jpg", ".jpeg", ".png", ".webp", ".gif", ".avif")


def main():
    rows = []
    for dirpath, _dirs, files in os.walk(MEDIA):
        if f"{os.sep}archive{os.sep}" in dirpath + os.sep:
            continue
        for fn in sorted(files):
            if not fn.lower().endswith(EXTS):
                continue
            path = os.path.join(dirpath, fn)
            try:
                with Image.open(path) as im:
                    w, h = im.size
            except Exception as exc:                       # noqa: BLE001
                print(f"  skip {fn}: {exc}", file=sys.stderr)
                continue
            url = "/" + os.path.relpath(path, ROOT).replace(os.sep, "/")
            # Liquid cannot use a slash-bearing string as a hash key, so the key
            # is the basename; filenames across the media tree are unique.
            rows.append((fn, url, w, h))

    seen = {}
    for fn, url, w, h in rows:
        if fn in seen:
            print(f"  WARNING duplicate basename: {fn}", file=sys.stderr)
        seen[fn] = (url, w, h)

    with open(OUT, "w") as fh:
        fh.write("# Generated by tools/index-images.py — do not edit by hand.\n")
        fh.write("# Keyed on filename. `max` is the widest CSS pixel width at which\n")
        fh.write("# the image still renders at 2x, i.e. the point beyond which it\n")
        fh.write("# would be upscaled.\n")
        for fn, (url, w, h) in sorted(seen.items()):
            fh.write(f'"{fn}":\n  w: {w}\n  h: {h}\n  max: {w // 2}\n')

    print(f"index-images: {len(seen)} images indexed -> _data/imagemeta.yml")
    return 0


if __name__ == "__main__":
    sys.exit(main())
